---

- hosts: all
  gather_facts: false
  tasks:
    - name: "Check if python is installed"
      package_facts:
        manager: "auto"
    - name: "python test result"
      debug:
        msg: "python found"
      when: "'python' in ansible_facts.packages"
    - name: "python test result"
      debug:
        msg: "python NOT found"
      when: "'python' not in ansible_facts.packages"
    - name: install python
      package:
        name: nginx
        state: present
